using System;
using System.Collections.Generic;
using System.Text;
using System.Diagnostics;

namespace ProjectEuler.Problems
{
    static class PE2
    {
        /*
         * Question: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
         * the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
         * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
         * Answer: 4613732
         * Execution time: 0
         * Notes: 
         * Help: 
         */
        public static void P2()
        {
            Stopwatch stopwatch = new Stopwatch();
            stopwatch.Start();

            int prevNumber1 = 2, prevNumber2 = 1, currentNumber = 2, ans = 2;
            while (currentNumber<4000001)
            {
                currentNumber = prevNumber1 + prevNumber2;
                if (currentNumber % 2 == 0)
                {
                    ans += currentNumber;
                }
                prevNumber2 = prevNumber1;
                prevNumber1 = currentNumber;
            }

            stopwatch.Stop();
            Console.WriteLine($"The elapsed time is: {(double)stopwatch.ElapsedMilliseconds / 1000}");
            Console.Write(ans);
        }
    }
}
